# -*- coding: utf-8 -*-
"""Capesppg_docentes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RInwfsq2rR3Z2aqlClU1lt7HiT0dscv
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import sklearn as skt

"""- Após agrupar as bases relacionadas a Docentes de 2013 a 2019, criei o dataset único abaixo:"""

path = '/content/drive/My Drive/bases_capesppg_docentes/capesppg_docentes_2013-2019.csv'
df = pd.read_csv(path)

"""- Visualizando os dados do dataset:"""

df.head()

"""- Demonstrando de forma visual que há dados dos anos 2013 à 2019 neste dataset:"""

sns.countplot(x='AN_BASE', data = df)

df.info()

"""- Agrupando os dados por Programa de Pós Graduação"""

grouped = df.groupby('CD_PROGRAMA_IES',as_index=False)
grouped.first()

"""- Erro ao analisar os conceitos dos programas:

As visualizações e agrupamento utilizando os conceitos dos programas apresentou erro em diversar situações. Vide exemplos abaixo:
"""

df.groupby('AN_BASE').mean()['CD_CONCEITO_PROGRAMA']

df.groupby('NM_PAIS_IES_TITULACAO').mean()['CD_CONCEITO_PROGRAMA'].round(2).sort_values(ascending=False).head(15)

"""Analisando os dados únicos da coluna Conceito, notei que o erro é devido a alguns conceitos estarem no formato string:"""

df['CD_CONCEITO_PROGRAMA'].unique()

"""Abaixo notamos que o conceito 'A' é um problema das bases dos anos 2018 e 2019. """

# alguns conceitos de programa são A - dropar todos os 'A'

df.query("CD_CONCEITO_PROGRAMA=='A'").groupby(['CD_PROGRAMA_IES','CD_CONCEITO_PROGRAMA', 'AN_BASE'], as_index=False).first()

df1 = df.query("CD_CONCEITO_PROGRAMA=='A'").groupby(['CD_PROGRAMA_IES','CD_CONCEITO_PROGRAMA', 'AN_BASE'], as_index=False).first()
df1['AN_BASE'].unique()

"""Testei pesquisando na base de dados 'Programa 2018' na tentativa de encontrar o conceito numérico - sem sucesso (também apresentava o conceito 'A'):"""

df.query("CD_CONCEITO_PROGRAMA=='A' and AN_BASE==2018").groupby(['CD_PROGRAMA_IES','CD_CONCEITO_PROGRAMA', 'AN_BASE'], as_index=False).first()

# Comprovamos que, após o groupby por cd_programa_ies, temos valores únicos de PPG
# O próximo passo é utilizar o aggregate e transformar algumas colunas em dados categoricos

x = df['CD_PROGRAMA_IES'].unique().tolist()
len(x)

